spring.application.name=VotingCalc
spring.datasource.url=jdbc:mysql://localhost:3306/votingAge
spring.datasource.username=root
spring.datasource.password=Harshi@465
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true